---
version: "3.8"
services:
  postgres_auth:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  postgres_order:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  auth:
    depends_on:
      - postgres_auth
    build: ./auth
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url" : "jdbc:postgresql://postgres_auth:5432/postgres?useSSL=false",
              "spring.datasource.username" : "postgres",
              "spring.datasource.password" : "postgres",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.liquibase.changeLog" : "classpath:db/changelog/db.changelog-master.yaml",
              "logging.level.liquibase" : "info"
            }'
  order:
    depends_on:
      - postgres_order
    build: ./order
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url" : "jdbc:postgresql://postgres_order:5432/postgres?useSSL=false",
              "spring.datasource.username" : "postgres",
              "spring.datasource.password" : "postgres",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.liquibase.changeLog" : "classpath:db/changelog/db.changelog-master.yaml",
              "logging.level.liquibase" : "info",
              "auth.url.get-user-data" : "http://auth:8080/get-user-data"
            }'

